services:
  dstgbot:
    image: ghcr.io/korjavin/dstgbot:latest
    restart: unless-stopped
    container_name: ${APP_NAME:-dstgbot}
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DEEPSEEK_APIKEY=${DEEPSEEK_APIKEY}
      - TG_GROUP_ID=${TG_GROUP_ID}
      - SYSTEM_MSG=${SYSTEM_MSG}
    networks:
      - proxy

networks:
  proxy:
    name: ${NETWORK_NAME}
    external: true
